In [2]:
import numpy as np

In [8]:
array_1d = np.array([1,2,3,4,5])
print(array_1d.ndim) # Numero de dimensoes
print(array_1d.shape) # Formato do array
array_1d

1
(5,)


array([1, 2, 3, 4, 5])

In [ ]:
array_2d = np.array([[3,2,1],[6,5,4]])
print(array_2d.ndim)  # Numero de dimensoes
print(array_2d.shape)  # Formato do array
array_2d
# Matrizes, tabelas de dados, imagens em escala de cinza

2
(2, 3)


array([[3, 2, 1],
       [6, 5, 4]])

In [ ]:
array_3d = np.array([[[3, 2, 1], [6, 5, 4], [9,8,7]]])
print(array_3d.ndim)  # Numero de dimensoes
print(array_3d.shape)  # Formato do array
array_3d
# Imagens em cores(cada matriz representando um canal de cor, RGB)

3
(1, 3, 3)


array([[[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]])

In [14]:
array_4d = np.zeros((2,3,5,6))
print(array_4d.ndim)  # Numero de dimensoes
print(array_4d.shape)  # Formato do array
array_4d

4
(2, 3, 5, 6)


array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
        