In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [5]:
# Adição
soma = np.add(array, 22)
soma


array([23, 24, 25, 26, 27])

In [6]:
# Subtracao
sub = np.subtract(array, 5)
sub

array([-4, -3, -2, -1,  0])

In [ ]:
# Multiplicacao
mult = np.multiply(array, 3)
mult

array([ 3,  6,  9, 12, 15])

In [8]:
# Divisao
div = np.divide(array, 2)
div

array([0.5, 1. , 1.5, 2. , 2.5])

In [9]:
# Funções Trigonometricas
seno = np.sin(array)
seno

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [10]:
cosseno = np.cos(array)
cosseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [11]:
# Funcoes Estastisticas
media = np.mean(array)
media

np.float64(3.0)

In [12]:
desvio_padrao = np.std(array)
desvio_padrao

np.float64(1.4142135623730951)

In [13]:
# Funcoes de Comparacao
comparacao_maior_que_3 = array > 3
comparacao_maior_que_3

array([False, False, False,  True,  True])

In [14]:
# Combinando Funcoes
resultado = np.sqrt(array) + np.power(array, 2)
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [19]:
# Funcoes exponenciais
exponencial = np.exp(array)
exponencial


array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [20]:
# Funcoes de logaritmos
logaritmo = np.log(array)
logaritmo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [21]:
# Funcoes de Arredondamento
arredondar = np.round(array/2)
arredondar

array([0., 1., 2., 2., 2.])

In [22]:
# Funcoes de Potencia
potencia = np.power(array, 3)
potencia

array([  1,   8,  27,  64, 125])