Copy
* Uma nova copia do array é criada em memoria, significando que as duas matrizes são independentes.

View
- Não é criada uma nova copy na memoria, a view compartilha os mesmos dados que o array original.

In [2]:
import numpy as np

In [3]:
array_original = np.array([[1,2,3],
                           [4,5,6],
                           [7,8,9]])

array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Cópia rasa (view)
array_view = array_original[1:,1:]
array_view

array([[5, 6],
       [8, 9]])

In [5]:
array_view[0,0] = 99
array_view

array([[99,  6],
       [ 8,  9]])

In [6]:
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [7]:
# Cópia profunda (copy)
array_copia = array_original.copy()
array_copia

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [8]:
array_copia[0,0] = 125
array_original

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [9]:
array_copia

array([[125,   2,   3],
       [  4,  99,   6],
       [  7,   8,   9]])