In [1]:
import numpy as np

In [3]:
array1 = np.array([1,2,3])
array2 = np.array([9,8,7])

In [5]:
# Concatenando arrays
novo_array = np.concatenate((array1, array2))
novo_array

array([1, 2, 3, 9, 8, 7])

In [6]:
# Criando arrays para nomes e notas
nomes = np.array(["Alice", "Marcelo", "Maquerle"])
notas = np.array([99,55,66])
notas_fisica = np.array([88,44,22])

In [7]:
# Usando np.vstack para empilhar verticalmente os dados
dados_estudantes = np.vstack((nomes,notas,notas_fisica))
dados_estudantes

array([['Alice', 'Marcelo', 'Maquerle'],
       ['99', '55', '66'],
       ['88', '44', '22']], dtype='<U21')

In [8]:
# Usando np.hstack para empilhar horizontalmente
matriz_notas = np.column_stack((notas,notas_fisica))
matriz_notas

array([[99, 88],
       [55, 44],
       [66, 22]])

In [9]:
#Adicionando uma nova coluna com a media das notas
media_notas = np.mean(matriz_notas, axis=1)
matriz_final = np.column_stack((matriz_notas, media_notas))
matriz_final

array([[99. , 88. , 93.5],
       [55. , 44. , 49.5],
       [66. , 22. , 44. ]])