In [1]:
import numpy as np

In [2]:
array = np.array([9,7,8,3,5,6])
array

array([9, 7, 8, 3, 5, 6])

In [3]:
array_divididos = np.split(array, 3)
array_divididos

[array([9, 7]), array([8, 3]), array([5, 6])]

In [4]:
for i, value in enumerate(array_divididos):
    print(f"Parte {i+1} ->> {value}")

Parte 1 ->> [9 7]
Parte 2 ->> [8 3]
Parte 3 ->> [5 6]


In [12]:
#Criand um array 1d com temperaturas diarias de um mes (30 dias)
temperaturas = np.array([33,30,32,28,22,24,26,
                        32,29,25,22,21,
                        30,31,33,35,36,
                        22,22,21,20,25,
                        24,27,28,29,30,
                        32,33,31,22,26])
temperaturas

array([33, 30, 32, 28, 22, 24, 26, 32, 29, 25, 22, 21, 30, 31, 33, 35, 36,
       22, 22, 21, 20, 25, 24, 27, 28, 29, 30, 32, 33, 31, 22, 26])

In [13]:
# Dividindo as temperaturas em 4 semanas
semanas = np.split(temperaturas, 4)
semanas

[array([33, 30, 32, 28, 22, 24, 26, 32]),
 array([29, 25, 22, 21, 30, 31, 33, 35]),
 array([36, 22, 22, 21, 20, 25, 24, 27]),
 array([28, 29, 30, 32, 33, 31, 22, 26])]

In [14]:
for i,value in enumerate(semanas):
    print(f"Semana {i+1}: {value}")

Semana 1: [33 30 32 28 22 24 26 32]
Semana 2: [29 25 22 21 30 31 33 35]
Semana 3: [36 22 22 21 20 25 24 27]
Semana 4: [28 29 30 32 33 31 22 26]


In [15]:
medias_semanas = [np.mean(semana) for semana in semanas]
medias_semanas

[np.float64(28.375), np.float64(28.25), np.float64(24.625), np.float64(28.875)]

In [16]:
for i,value in enumerate(medias_semanas):
    print(f"Média da semana {i+1}: {value:.2f}ºC")

Média da semana 1: 28.38ºC
Média da semana 2: 28.25ºC
Média da semana 3: 24.62ºC
Média da semana 4: 28.88ºC
