In [1]:
import numpy as np

In [2]:
array = np.array([10,20,30,40,50])
array

array([10, 20, 30, 40, 50])

In [4]:
#Pesquisar a posicao valor 40
posicao = np.where(array==40)
posicao

(array([3]),)

In [5]:
#criar um array com notas de alunos
notas = np.array([55,88,99,66,11,22,33,44,55,69])
notas

array([55, 88, 99, 66, 11, 22, 33, 44, 55, 69])

In [6]:
#Pesquisar quais alunos foram aprovados (nota>60)
alunos_aprovados = np.where(notas>60)
alunos_aprovados

(array([1, 2, 3, 9]),)

In [7]:
notas[alunos_aprovados]

array([88, 99, 66, 69])

In [8]:
nota_maxima = np.max(notas)
nota_maxima

np.int64(99)

In [9]:
indice_maximo = np.argmax(notas)
indice_maximo

np.int64(2)