In [1]:
import numpy as np

In [2]:
array = np.array([[55,22,33, 99], 
                  [77,88,99, 88], 
                  [11,33,44, 66]])

print(array.ndim)
print(array.shape)
array

2
(3, 4)


array([[55, 22, 33, 99],
       [77, 88, 99, 88],
       [11, 33, 44, 66]])

In [3]:
# Buscar elemento na linha 1  e coluna 2
elemento = array[1,2]
elemento


np.int64(99)

In [7]:
# Pegar dados da primeira linha
linha_0 = array[0]
linha_0

array([55, 22, 33, 99])

In [9]:
# Acessando a coluna 1
coluna_1 = array[:,1]
coluna_1

array([22, 88, 33])

In [10]:
# Fatiando para obter um subarray
subarray = array[0:2, 1:3]
subarray

array([[22, 33],
       [88, 99]])

In [11]:
mascara = array > 50
mascara

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [False, False, False,  True]])

In [12]:
elementos_maiores_que_50 = array[mascara]
elementos_maiores_que_50

array([55, 99, 77, 88, 99, 88, 66])

In [13]:
array[1,1] = 175
array

array([[ 55,  22,  33,  99],
       [ 77, 175,  99,  88],
       [ 11,  33,  44,  66]])