In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3,5,6],
                  [9,8,7,5,6],
                  [10,13,14,55,66],
                  [20,22,35,64,88]])

array

array([[ 1,  2,  3,  5,  6],
       [ 9,  8,  7,  5,  6],
       [10, 13, 14, 55, 66],
       [20, 22, 35, 64, 88]])

In [3]:
# FAtiando as duas primeiras linhas
fatianhando_linhas = array[0:2,:]
fatianhando_linhas

array([[1, 2, 3, 5, 6],
       [9, 8, 7, 5, 6]])

In [5]:
# Fatiando as tres primeiras colunas
fatianhando_colunas = array[:,0:3]
fatianhando_colunas

array([[ 1,  2,  3],
       [ 9,  8,  7],
       [10, 13, 14],
       [20, 22, 35]])

In [6]:
subarray_central = array[1:3, 1:3]
subarray_central

array([[ 8,  7],
       [13, 14]])

In [7]:
subarray_lateral = array[2:4, 3:5]
subarray_lateral

array([[55, 66],
       [64, 88]])

In [8]:
# Modificar um subarray
array[1:3, 1:3] = [[99,100], [101,102]]
array

array([[  1,   2,   3,   5,   6],
       [  9,  99, 100,   5,   6],
       [ 10, 101, 102,  55,  66],
       [ 20,  22,  35,  64,  88]])