In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Iteração simples usando loop for
for x in array:
    print(x)
    for y in x:
        print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


In [6]:
# Usando np.nditer para uma iteração mais eficiente
for valor in np.nditer(array):
    print(valor, end=" ")

1 2 3 4 5 6 7 8 9 

In [7]:
# Iteracao com condicao
for valor in np.nditer(array):
    if valor % 2 == 0:
        print(f"{valor} é par.")
    else:
        print(f"{valor} é impar.")

1 é impar.
2 é par.
3 é impar.
4 é par.
5 é impar.
6 é par.
7 é impar.
8 é par.
9 é impar.


In [8]:
# Iteração com Indices
for i in range(array.shape[0]):
    for x in range(array.shape[1]):
        print(f"Elemento na posição ({i}, {x}): {array[i,x]}")

Elemento na posição (0, 0): 1
Elemento na posição (0, 1): 2
Elemento na posição (0, 2): 3
Elemento na posição (1, 0): 4
Elemento na posição (1, 1): 5
Elemento na posição (1, 2): 6
Elemento na posição (2, 0): 7
Elemento na posição (2, 1): 8
Elemento na posição (2, 2): 9
